networks:
  gateway-network:
    driver: bridge

volumes:
  redis_data:
  prometheus_data:


services:

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - gateway-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    volumes:
      - ../config/prometheus.yml/:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - gateway-network


  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-container
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SERVER_DOMAIN=localhost
    networks:
      - gateway-network



